### ISSUE TITLE
polylines not scaling along with plot

### ISSUE THREAD

**Issue by zrichz** [Zyin055/Inspect-Embedding-Training#1]
great tool - but the polylines showing the best fit line and the polynomial fit are not scaling along with the rest of the chart. (the rolling averages are behaving correctly)
![20220111H256-3000-loss](https://user-images.githubusercontent.com/33601693/211843433-3f12838a-ee43-4032-a1e3-bb43cb57922f.jpg)

**Comment by Zyin055** [comment]
It may be because you have a relatively small number of data points. See if setting the loss logging to every step helps.

**Comment by zrichz** [comment]
Okay thanks will test if logging every step helps👍

**Comment by zrichz** [comment]
logging every step was the answer! - many thanks works fine :)
