### ISSUE TITLE
How are file names interpreted?

### ISSUE THREAD

**Issue by RainehDaze** [Zyin055/Inspect-Embedding-Training#10]
Interesting little thing I observed when I was looking at DreamArtist-generated embeddings: both the positive (embedding-XXXX.pt) and negative (embedding-XXXX-neg.pt) files are read and loaded. I'm not _quite_ sure what gets done with the negatives.

**Comment by Zyin055** [comment]
Looking over the code I think the behavior is undefined for that case. It depends on the order in which the files are read, and whether or not it reads the X.pt or X-neg.pt file first.
What would be a good way to handle that case? should it just ignore "-neg.pt" files?

**Comment by RainehDaze** [comment]
Ignoring them would probably be best; these are technically just two entirely separate embeddings, which can have different numbers of vectors per embedding (they just train at the same time).

**Comment by Zyin055** [comment]
I don't have the DreamArtist extension installed so let me know if that update fixes the issue and ignores the -neg.pt files. I just manually renamed some to end with -neg.pt for testing on my side.

**Comment by RainehDaze** [comment]
Looks good, skips the appropriate files. Only thing that'd help with DreamArtist embeddings more is the ability to specify the loss file manually--it's got a different name than the textual inversion one, so it has to be renamed for graphing. xD

**Comment by Zyin055** [comment]
Can you upload a screenshot of what the training folder looks like with the differently named .csv file?

**Comment by RainehDaze** [comment]
![image](https://user-images.githubusercontent.com/7266470/216789133-47630591-0686-44ee-8d71-18bb59141aa6.png)
Same structure, it's just called prompt_tuning_loss.csv instead.

**Comment by Zyin055** [comment]
As long as it has the same data format, that update should load it.

**Comment by RainehDaze** [comment]
![image](https://user-images.githubusercontent.com/7266470/216790103-405f79da-bf52-47e7-9d36-ad9285755b84.png)

Yup, that works (although, as usual, the loss over time tells me pretty much nothing--are the blue and purple the trend over time or something? And why so short? xD)

**Comment by Zyin055** [comment]
The colored lines require more data points to work properly. You'd need to increase the rate at which the loss is saved in the A1111 settings, I set mine to 1.
