### ISSUE TITLE
Units, legend

### ISSUE THREAD

**Issue by larssn** [Zyin055/Inspect-Embedding-Training#13]
I think it would be helpful if the generated graph had units and a legend for the lines.

Just started using this fine tool, and I don't really understand what, say, the lines represent.

So consider this a small feature request.

**Comment by Zyin055** [comment]
The lines represent the value of each vector, they have no units.

**Comment by larssn** [comment]
Alright so no units. But the lines have to mean something, like loss, strength, etc?

**Comment by Zyin055** [comment]
The vector values are used to calculate the strength and magnitude of the embedding.
