### ISSUE TITLE
Error with --file argument

### ISSUE THREAD

**Issue by Rudy34160** [Zyin055/Inspect-Embedding-Training#15]
Hi,
Great script to analyze our integrations!
But I encounter the following error when I want to analyze a particular file:

![image](https://user-images.githubusercontent.com/118270456/219817815-a267ce1d-9417-42ec-84a2-0280382521ad.png)
However, I think that the file locations are respected:

![image](https://user-images.githubusercontent.com/118270456/219818064-3d519894-15c3-488f-8a3b-45f809858fcd.png)

If you can tell me where my error comes from...

**Comment by Zyin055** [comment]
Your command window is opened at `C:\users\Admin`, so its looking for `C:\users\Admin\ejai18.pt`. Either open the command window in the correct folder (or `cd` to it) or supply the full file path to ejai18.pt

**Comment by Rudy34160** [comment]
Thank you so much ! Big mistake on my part...

As requested in this other post, where can we find more relevant information on the application of this script in our trainings?
https://github.com/Zyin055/Inspect-Embedding-Training/issues/4#issuecomment-1416185069

**Comment by Zyin055** [comment]
Embedding training is not a well defined science. As mentioned in that other post, the purpose of this script is to attempt to figure out what is important and potentially learn more about how they work. There is no clear cut info yet.
