### ISSUE TITLE
Inspect an existing embedding file

### ISSUE THREAD

**Issue by Rudy34160** [Zyin055/Inspect-Embedding-Training#16]
I wanted to try this: _If all you want to do is inspect an existing embedding file that you downloaded from the internet, you can use --file EmbeddingName with the EmbeddingName.pt file next to the script._

Doesn't matter for the source of the embedding, but it doesn't seem to work with "embedding.bin": These file types don't work like "embeddings.pt" files? Or would it be necessary to use a different script depending on the type of file to be analyzed?

**Comment by Zyin055** [comment]
I've only used A1111 to train embeddings so I've only gotten .pt files out of it. Does renaming the .bin file to .pt work?

**Comment by Rudy34160** [comment]
_> I've only used A1111 to train embeddings so I've only gotten .pt files out of it. Does renaming the .bin file to .pt work?_

 No. By example, I try with this embedding _https://civitai.com/models/8235/lili-reinhart_, and rename the .bin file to .pt : Script don't work.
Both types of files seem to work under A1111, but their construction must be different I guess. I thought I could try parsing the .bins to understand a bit more about the parameters to use to get a good embedding.

**Comment by Zyin055** [comment]
Just updated the script to accept .bin embedding file format. The .bin embedding you supplied didn't have any additional metadata attached to it, just the raw vector values (tensors). This lets you get the strength/magnitude, but not other stuff like step count or model it was trained on. Try it out and let me know if it works for you.

**Comment by Rudy34160** [comment]
It works perfectly. It seems that the .bin files do not allow reading the embedding build data.
Thanks for the updated script!
