### ISSUE TITLE
Another type of .pt file ? 🤔

### ISSUE THREAD

**Issue by Rudy34160** [Zyin055/Inspect-Embedding-Training#17]
It works perfectly. It seems that the .bin files do not allow reading the embedding build data.
Thanks for the updated script!

_Originally posted by @Rudy34160 in https://github.com/Zyin055/Inspect-Embedding-Training/issues/16#issuecomment-1436885426_

**Comment by Rudy34160** [comment]
I'm trying to analyze a new embedding to understand its creation process: I get a new error, despite the file being a .pt:

![image](https://user-images.githubusercontent.com/118270456/220167269-f0fa41dd-5554-4918-9143-add6a3e7e409.png)
 
Link to relevant file: https://civitai.com/models/8860/scg-emotions-pack-simple-embeds-for-easily-controlling-a-variety-of-emotions-for-all-15-models-and-merges

**Comment by Zyin055** [comment]
The newest update should address different internal embedding data formats compared to what Automatic1111 creates.

**Comment by Rudy34160** [comment]
> The newest update should address different internal embedding data formats compared to what Automatic1111 creates.

So it's possible that the link embeds aren't from A1111?

**Comment by Zyin055** [comment]
Either that or they manipulated the internal data to hide things like step count, model it was trained on, etc.
