### ISSUE TITLE
.bin vs .pt

### ISSUE THREAD

**Issue by Rudy34160** [Zyin055/Inspect-Embedding-Training#18]
Either that or they manipulated the internal data to hide things like step count, model it was trained on, etc.

_Originally posted by @Zyin055 in https://github.com/Zyin055/Inspect-Embedding-Training/issues/17#issuecomment-1437419232_

Indeed, the .bin generated do not come from a training run with A1111, but with the script of this type of Colab: https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers /sd_textual_inversion_training.ipynb?authuser=2#scrollTo=B7xH_7tgvRDK
Why couldn't the "Inspection" script retrieve the parameter data from this type of file? 🤔

**Comment by Rudy34160** [comment]
Maybe it's due to this part of the script 🤔:

![image](https://user-images.githubusercontent.com/118270456/222405453-1ad1472e-05d1-492d-a425-a25a0dbce1ce.png)

**Comment by Zyin055** [comment]
As of 2/19 we do support .bin files. The issue is that they probably aren't saving that extra metadata with the embedding. Any extra data we read and print:
https://github.com/Zyin055/Inspect-Embedding-Training/blob/main/inspect_embedding_training.py#L260-L263
