### ISSUE TITLE
Can you add option to calculate strength of given folder? all files inside that folder?

### ISSUE THREAD

**Issue by FurkanGozukara** [Zyin055/Inspect-Embedding-Training#3]
e.g. we give folder path it calculates weight strength of all files so that we can see the overtraining pattern of embeddings

for example I usually save check point every 10 epoch during training so I have a lot of pt files

thank you

**Comment by FurkanGozukara** [comment]
@Zyin055 awesome ty
hopefully i am going to show in my upcoming tutorial video

this 0.2 strength is based on your experience or any math related explanation behind it?

**Comment by Zyin055** [comment]
Just based on my experiences. There is no mathematical best number, it's just a tradeoff between flexibility and fit-ness.

**Comment by FurkanGozukara** [comment]
> Just based on my experiences. There is no mathematical best number, it's just a tradeoff between flexibility and fit-ness.

perhaps if we dont provide folder path and just provide folder argument, it can try the currently located folder. I am just trying to make it easier for people who is going to watch my video :D

**Comment by Zyin055** [comment]
I'd have to redo the whole launch arg parsing code, not willing to do it just for that feature.

**Comment by FurkanGozukara** [comment]
> I'd have to redo the whole launch arg parsing code, not willing to do it just for that feature.

ok it is fine ty so much for this update. i will clearly explain it
