### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by ReidTissing** [Zyin055/Inspect-Embedding-Training#6]
With or without explicit --file, I get the following error:
`Traceback (most recent call last):
  File "inspect_embedding_training.py", line 23, in <module>
    GRAPH_IMAGE_SIZE: tuple[int, int] = (19, 9)   # (X,Y) tuple in inches (multiply by 100 for (X,Y) pixel size for the output graphs)
TypeError: 'type' object is not subscriptable`

**Comment by Zyin055** [comment]
What version of Python are you using? Open a command prompt and type `python` to see.

**Comment by ReidTissing** [comment]
yeah, that was my bad. Didn't realize it wasn't using Python 3.10.
