### ISSUE TITLE
Adapt this script for Hypernetworks?

### ISSUE THREAD

**Issue by Woisek** [Zyin055/Inspect-Embedding-Training#8]
As in the title.
Would that be possible to also use it on Hypernetworks? That would be awesome.

**Comment by Zyin055** [comment]
No. Hypernetworks have a different file structure and 20,000 times more data.

**Comment by Woisek** [comment]
OK. At least as a seperate script?

**Comment by Zyin055** [comment]
If someone wants to do that they can, but I'm not interested in doing it.

**Comment by Woisek** [comment]
Allright, thanks.
